[package]
name = "raven"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }
spinners = "4.1.0"
tokio = { version = "1", features = ["full"] }
